source 'https://rubygems.org'

  # Sass, Compass and extensions.
  gem 'sass', '~>3.3.6'  # Sass.
  gem 'compass', '~>1.0.0.alpha.19' # Framework built on Sass.
  gem 'breakpoint', '2.4.1' # Manages CSS media queries.
